
test {
    _ = @import("build_messages_for_agent_prompt_test.zig");
    _ = @import("build_messages_for_agent_prompt_design_canvas_test.zig"); // design-mode-scrollbar-fix — iframe scrollbar guidance in BuildDesignCanvasPrompt
    _ = @import("handle_tool_test.zig");
    _ = @import("inherited_context_test.zig");
    _ = @import("routines/model_test.zig");
    _ = @import("routines/cron_test.zig");
    _ = @import("routines/fire_test.zig");
    _ = @import("routines/scheduler_test.zig");
    _ = @import("save_agent_test.zig");
    _ = @import("save_skill_test.zig");
    _ = @import("agentic_loop/workflow_compaction_envelope_test.zig");
    _ = @import("agentic_loop/workflow_retry_delay_test.zig");
    // Inline retry-loop hygiene tests (CallResponse deinit, literal-free
    // errdefer, stale retry-cause capture) live in workflow.zig itself —
    // registered here so zig build test actually runs them.
    _ = @import("agentic_loop/workflow.zig");
    _ = @import("compaction_config_threshold_test.zig");
    _ = @import("http_handlers/nalar_config_put_test.zig");
    _ = @import("http_handlers/nalar_config_put_parse_test.zig");
    _ = @import("http_handlers/nalar_config_get_test.zig");
    _ = @import("http_handlers/nalar_config_profile_delete_test.zig");
    _ = @import("http_handlers/sse_handshake_test.zig");
    _ = @import("http_handlers/task_update_test.zig");
    _ = @import("http_handlers/task_delete_test.zig");
    _ = @import("http_handlers/task_mark_human_touched_test.zig"); // Chunk 3 — PUT /tasks/:id/touched + Chunk 4 SSE wire
    _ = @import("http_handlers/task_touch_propagation_test.zig"); // Chunk 5 — stamp last_human_touched_at from existing mutating handlers
    _ = @import("http_handlers/tasks_list_test.zig");
    _ = @import("http_handlers/task_create_routines_test.zig");
    _ = @import("http_handlers/task_create_memory_test.zig");
    _ = @import("http_handlers/task_create_description_test.zig");  // Migration 062 description in create path
    _ = @import("http_handlers/task_update_routines_test.zig");
    _ = @import("http_handlers/routines_run_test.zig");
    _ = @import("http_handlers/routines_list_test.zig");
    _ = @import("http_handlers/memories_crud_test.zig");
    _ = @import("http_handlers/local_memories_crud_test.zig");
    _ = @import("http_handlers/frontend_log_post_test.zig"); // Chunk 2 of frontend-error-logs
    _ = @import("http_handlers/frontend_log_get_test.zig");  // Chunk 3 of frontend-error-logs
    _ = @import("llm_history_is_input_output_test.zig");
    _ = @import("llm_history_routines_test.zig");
    _ = @import("llm_history_compacted_messages_test.zig");
    _ = @import("llm_history_search_messages_fts_test.zig"); // search_history rewrite (Chunk 2)
    _ = @import("llm_history_worker_info_test.zig"); // NEW: sprint 2 "git worktree cwd, worker"
    _ = @import("llm_history_description_test.zig"); // Migration 062 description propagation
    _ = @import("llm_history_notification_test.zig"); // Migration 065 — kanban needs_human_review + updateTaskLastHumanTouchedAt
    _ = @import("compaction_long_context_test.zig");
    _ = @import("http_handlers/workspaces_reorder_test.zig");
    _ = @import("http_handlers/workspace_items_reorder_test.zig");
    _ = @import("http_handlers/task_pin_test.zig");
    _ = @import("design_io_test.zig");
    _ = @import("design_model_test.zig");
    _ = @import("design_model_parent_id_test.zig"); // 2026-07-28-grouped-layers (Chunk 1) — parent_id round-trip
    _ = @import("migration_057_test.zig");  // stays at this path; imported by src/migrations/test_runner.zig via relative path
    _ = @import("migration_063_runtime_test.zig");  // Chunk 1 — sessions auto_retry + finish_reason runtime CRUD
    _ = @import("http_handlers/session_create_migration_063_test.zig");  // Chunk 3 Task 3.1 — POST /api/session static-contract
    _ = @import("http_handlers/session_update_migration_063_test.zig");  // Chunk 3 Task 3.2 — PUT /api/session/:id static-contract
    _ = @import("kanban_model_test.zig");
    _ = @import("kanban_model_test_description.zig");
    _ = @import("kanban_copy_spec_test.zig");
    _ = @import("http_handlers/tasks_reorder_pinned_test.zig");
    _ = @import("http_handlers/git_worktree_info_test.zig");
    _ = @import("http_handlers/git_pr_create_test.zig");
    _ = @import("http_handlers/git_status_test.zig");
    _ = @import("http_handlers/workspace_items_create_kanban_test.zig");
    _ = @import("http_handlers/workspace_items_create_empty_name_test.zig");
    _ = @import("workspace_items_update_name_test.zig");
    _ = @import("http_handlers/kanban_columns_list_test.zig");
    _ = @import("http_handlers/kanban_columns_create_test.zig");
    _ = @import("http_handlers/kanban_columns_update_test.zig");
    _ = @import("http_handlers/kanban_columns_delete_test.zig");
    _ = @import("http_handlers/design_pages_list_test.zig");
    _ = @import("http_handlers/design_pages_create_test.zig");
    _ = @import("http_handlers/design_items_create_test.zig");
    _ = @import("http_handlers/design_pages_get_test.zig");
_ = @import("http_handlers/design_pages_update_test.zig");
    _ = @import("http_handlers/design_pages_delete_test.zig"); // 2026-07-25-design-page-delete-button (Chunk 1)
    _ = @import("http_handlers/design_elements_create_test.zig");
    _ = @import("http_handlers/design_elements_update_test.zig");
    _ = @import("http_handlers/design_elements_delete_test.zig");
    _ = @import("http_handlers/design_elements_html_get_test.zig");
    _ = @import("http_handlers/design_elements_html_update_test.zig");
    _ = @import("http_handlers/design_elements_geometry_update_test.zig");
    _ = @import("http_handlers/kanban_copy_spec_test.zig");
    _ = @import("http_handlers/tasks_move_test.zig");
    _ = @import("http_handlers/tasks_create_kanban_test.zig");
    _ = @import("http_handlers/tasks_create_value_alloc_test.zig");
    _ = @import("http_handlers/system_prompt_get_test.zig");
    _ = @import("http_handlers/unified_events_sse_test.zig");
    // _ = @import("session_helpers_test.zig"); // DISABLED - requires std.Io which needs Init
    // _ = @import("session_table_test.zig"); // DISABLED - requires std.Io which needs Init
    _ = @import("get_session_list_test.zig");
    // _ = @import("transform_llm_history_to_agent_messages_test.zig"); // DISABLED - pre-existing type mismatch (TUIHistory vs LLMHistory) on main
    _ = @import("on_event_sent_sanitize_test.zig");
    _ = @import("on_event_sent_design_test.zig");
    _ = @import("gitignore_vendor_sqlite3_test.zig");
    _ = @import("../../modules/agent/tools/show_preview_test.zig");
    // _ = @import("extract_base64_image_urls_test.zig"); // DISABLED - 9 failing tests (investigation shows std.testing.expectEqualStrings has a bug with literal strings)
    // _ = @import("session_db_test.zig"); // DISABLED - pre-existing test errors (see session_db_test.zig for details)
    _ = @import("agentic_loop/test_runner.zig");
    _ = @import("handle_tool.zig");
}
