// GENERATED by tools/codegen_webapp_assets.zig — DO NOT EDIT
// To regenerate: zig build codegen:webapp-assets

const std = @import("std");

pub const Asset = struct {
    /// Path as served by the webserver, e.g. "/assets/index-abc.js"
    path: []const u8,
    /// File contents (use as-is; do not modify).
    content: []const u8,
    /// Inferred MIME type with charset for text/* types.
    mime: []const u8,
};
pub const assets: []const Asset = &.{
};
