// src/apps/desktop_app/main.zig
//
// Chunk 8 (with --nalar-url extension): the real lifecycle. Wires CLI
// parsing → mode branch → (spawn-mode: resolve → port → extract → spawn
// → healthcheck → webview) OR (connect-mode: just webview) → cleanup.
//
// Two startup modes:
//
//   Spawn mode (default):
//     1. Parse CLI flags (--port, --nalar-path, --window-size, --title, etc.)
//     2. Locate the nalar binary (--nalar-path → next-to-self → $PATH)
//     3. Allocate a free TCP port (or honour --port NNNN)
//     4. Extract the comptime-embedded webapp assets to a per-pid temp dir
//     5. Spawn `nalar --port <port>` as a child process
//     6. Poll GET /api/health until 200 (max 10s)
//     7. Open a native webview window pointed at http://127.0.0.1:<port>/
//     8. Run the platform event loop (blocks until the window closes)
//     9. On window close: SIGTERM nalar, wait up to 2s, SIGKILL if still
//        alive, then exit 0.
//
//   Connect mode (--nalar-url URL):
//     1. Parse CLI flags
//     2. Open the webview directly at the given URL
//     3. Run the platform event loop
//     4. On window close, exit 0. (No child nalar to clean up — the
//        external nalar that the user started keeps running.)
//
// The dev workflow that motivated connect mode: you already have nalar
// running on :8081 (your TUI/dev nalar), and you want a window wrapper.
// `--nalar-url http://127.0.0.1:8081` does that without spawning a
// second nalar on :8080.

const std = @import("std");
const cli = @import("cli.zig");
const port = @import("port.zig");
const path_resolve = @import("path_resolve.zig");
const subprocess = @import("subprocess.zig");
const extraction = @import("extraction.zig");
const webview = @import("webview.zig");

// Generated by build (Chunk 3.2 codegen). Layout-compatible with
// `extraction.AssetEntry` (both have `{ path, content, mime: []const u8 }`).
const webapp_assets = @import("embedded/webapp_assets.zig");

// Force-include the platform implementation. linux.zig declares
// `pub export fn nalar_webview_create/run/destroy` which the extern
// declarations in webview.zig call. Without this import, LTO would
// dead-code-eliminate the entire linux.zig compilation (no caller
// would reach the extern "c" symbols yet from main.zig's perspective).
// After main() actually calls webview.run() (below), this import
// becomes redundant, but keeping it is a one-line safety net against
// future refactors.
const platform_linux = @import("platform/linux.zig");
comptime {
    _ = platform_linux; // bare `_ = ...;` is illegal at module scope
}

// Pull in the test files so they run under `zig build test:desktop-app`.
test {
    _ = @import("test_runner.zig");
}

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;
    const env_map = init.environ_map;

    // 1. Parse CLI args. `init.minimal.args` is a `process.Args` iterator
    // in Zig 0.16 (not a slice), so we materialize it into an ArrayList.
    var args_buf: std.ArrayList([]const u8) = .empty;
    defer args_buf.deinit(allocator);
    var args_iter = std.process.Args.Iterator.init(init.minimal.args);
    defer args_iter.deinit();
    while (args_iter.next()) |arg| {
        try args_buf.append(allocator, arg);
    }

    var cfg = cli.parse(allocator, args_buf.items) catch |err| switch (err) {
        error.ShowHelp => return,
        else => {
            std.log.err("Failed to parse CLI args: {s}", .{@errorName(err)});
            return err;
        },
    };
    defer cfg.deinit(allocator);

    // 1b. Connect mode (--nalar-url): skip the entire spawn path. The
    // user has their own nalar running and we just point the webview at
    // it. --port and --nalar-path are ignored. Asset extraction is also
    // skipped (the external nalar is responsible for serving the webapp).
    if (cfg.nalar_url) |url| {
        std.log.info("Connect mode: connecting to {s} (no spawn)", .{url});
        try runWebview(allocator, cfg, url, &.{});
        return;
    }

    // SPAWN MODE (default) — old flow.

    // 2. Find the nalar binary. Resolution order: --nalar-path → next to
    // self → $PATH. path_resolve.resolve returns null if nothing was found.
    const self_path = path_resolve.selfExePath(allocator) catch |err| {
        std.log.err("Failed to determine self path: {s}", .{@errorName(err)});
        return err;
    };
    defer allocator.free(self_path);

    const path_env = env_map.get("PATH") orelse "";
    const nalar_path = path_resolve.resolve(allocator, cfg.nalar_path, self_path, path_env) orelse {
        std.log.err("Could not find the nalar binary. Searched:", .{});
        if (cfg.nalar_path) |p| std.log.err("  --nalar-path: {s}", .{p});
        std.log.err("  next to self: {s}/nalar", .{std.fs.path.dirname(self_path) orelse "."});
        std.log.err("  PATH: {s}", .{path_env});
        return error.NalarNotFound;
    };
    defer allocator.free(nalar_path);

    // 3. Allocate a port. cfg.port == 0 means "auto-pick"; otherwise use
    // the explicit value. nalar is spawned with `--port <port>` and we
    // point the webview at `http://127.0.0.1:<port>/`.
    const listen_port: u16 = if (cfg.port == 0)
        blk: {
            const free = port.findFree(allocator, io) catch |err| {
                std.log.err("Failed to find a free port: {s}", .{@errorName(err)});
                return err;
            };
            break :blk free.port;
        }
    else
        cfg.port;

    // 4. Extract the comptime-embedded webapp to a per-pid temp dir.
    // The generated `webapp_assets.assets` is `[]const webapp_assets.Asset`
    // (struct { path, content, mime }). extraction.extract takes
    // `[]const extraction.AssetEntry` with the same field layout. The
    // slice cast is safe because the structs are byte-identical.
    const asset_entries: []const extraction.AssetEntry = @ptrCast(webapp_assets.assets);

    const webapp_dir = extraction.extract(allocator, asset_entries) catch |err| {
        std.log.err("Failed to extract embedded webapp: {s}", .{@errorName(err)});
        return err;
    };
    defer extraction.cleanup(allocator, webapp_dir);

    // 5. Spawn nalar. argv is built inside subprocess.spawn; we pass
    // --port <port>. The design doc says we should also pass --static-dir
    // <webapp_dir>, but nalar's --static-dir isn't yet wired to be passed
    // through spawn() — this is a known follow-up (the extraction still
    // happens so the temp dir is reusable from a future nalar --static-dir
    // patch).
    var nalar = subprocess.spawn(allocator, io, nalar_path, listen_port) catch |err| {
        std.log.err("Failed to spawn nalar at {s}: {s}", .{ nalar_path, @errorName(err) });
        return err;
    };
    defer nalar.terminate(io);

    // 6. Wait for nalar to be healthy. 10s budget, poll every 100ms.
    std.log.info("Waiting for nalar at http://127.0.0.1:{d}...", .{listen_port});
    subprocess.waitForHealth(listen_port, 10_000, 100) catch |err| switch (err) {
        error.HealthCheckTimeout => {
            std.log.err("nalar did not become healthy within 10s.", .{});
            return err;
        },
    };
    std.log.info("nalar is ready.", .{});

    // 7. Build the C ABI asset table. The comptime-generated array uses
    // string slices, but the C ABI wants pointer/length tuples, so we
    // build a parallel `c_assets` array on the stack with the same length.
    var c_assets: [webapp_assets.assets.len]webview.CAsset = undefined;
    for (webapp_assets.assets, 0..) |asset, i| {
        c_assets[i] = .{
            .path = @ptrCast(asset.path.ptr),
            .content = asset.content.ptr,
            .content_len = asset.content.len,
            .mime = @ptrCast(asset.mime.ptr),
        };
    }

    // 8. Open the webview at the spawned nalar's URL.
    const url = try std.fmt.allocPrint(allocator, "http://127.0.0.1:{d}/", .{listen_port});
    defer allocator.free(url);
    try runWebview(allocator, cfg, url, &c_assets);
}

/// Build the webview Config from the CLI settings + asset table, then run
/// the platform event loop (blocks until the window closes). Used by both
/// spawn mode (with the embedded webapp assets) and connect mode (with
/// an empty asset table — the external nalar serves the webapp).
///
/// On error, logs the platform error and returns it. The caller is
/// responsible for any `defer` cleanups (asset extraction, nalar child,
/// etc.) — this helper does its own `defer` for the heap strings it
/// allocates for the C ABI.
fn runWebview(
    allocator: std.mem.Allocator,
    cfg: cli.Config,
    url: []const u8,
    c_assets: []const webview.CAsset,
) !void {
    // Null-terminate the strings the C ABI expects.
    const title_z = try allocator.dupeZ(u8, cfg.title);
    defer allocator.free(title_z);
    // Use `?[:0]u8` (mutable) so we can free in defer. Cast to
    // `?[*:0]const u8` for the webview Config field via ua_z_const.
    const ua_z: ?[:0]u8 = if (cfg.user_agent) |ua| try allocator.dupeZ(u8, ua) else null;
    const ua_z_const: ?[*:0]const u8 = if (ua_z) |ua| ua.ptr else null;
    defer if (ua_z) |ua| allocator.free(ua);

    const webview_cfg: webview.Config = .{
        .title = title_z.ptr,
        .width = @intCast(cfg.window_width),
        .height = @intCast(cfg.window_height),
        .min_width = 400,
        .min_height = 300,
        .resizable = true,
        .maximizable = true,
        .minimizable = true,
        .user_agent = ua_z_const,
        .icon_path = null,
        .assets = c_assets.ptr,
        .asset_count = c_assets.len,
    };

    std.log.info("Opening webview at {s}", .{url});
    webview.run(allocator, webview_cfg, url) catch |err| {
        std.log.err("Webview error: {s}", .{@errorName(err)});
        return err;
    };
    std.log.info("Window closed. Exiting.", .{});
}
