// src/apps/desktop_app/main.zig
//
// Chunk 8 (with --nalar-url extension): the real lifecycle. Wires CLI
// parsing → mode branch → (spawn-mode: resolve → port → extract → spawn
// → healthcheck → webview) OR (connect-mode: just webview) → cleanup.
//
// Two startup modes:
//
//   Spawn mode (default):
//     1. Parse CLI flags (--port, --nalar-path, --window-size, --title, etc.)
//     2. Locate the nalar binary (--nalar-path → next-to-self → $PATH)
//     3. Allocate a free TCP port (or honour --port NNNN)
//     4. Extract the comptime-embedded webapp assets to a per-pid temp dir
//     5. Spawn `nalar --port <port>` as a child process
//     6. Poll GET /health until 200 (max 10s)
//     7. Open a native webview window pointed at http://127.0.0.1:<port>/
//     8. Run the platform event loop (blocks until the window closes)
//     9. On window close: SIGTERM nalar, wait up to 2s, SIGKILL if still
//        alive, then exit 0.
//
//   Connect mode (--nalar-url URL):
//     1. Parse CLI flags
//     2. Open the webview directly at the given URL
//     3. Run the platform event loop
//     4. On window close, exit 0. (No child nalar to clean up — the
//        external nalar that the user started keeps running.)
//
// The dev workflow that motivated connect mode: you already have nalar
// running on :8081 (your TUI/dev nalar), and you want a window wrapper.
// `--nalar-url http://127.0.0.1:8081` does that without spawning a
// second nalar on :8080.

const std = @import("std");
const builtin = @import("builtin");
const cli = @import("cli.zig");
const port = @import("port.zig");
const path_resolve = @import("path_resolve.zig");
const subprocess = @import("subprocess.zig");
const extraction = @import("extraction.zig");
const webview_lib = @import("webview_lib.zig");
const attach = @import("attach.zig");
const nalarcore = @import("nalarcore");

// Generated by build (Chunk 3.2 codegen). Layout-compatible with
// `extraction.AssetEntry` (both have `{ path, content, mime: []const u8 }`).
const webapp_assets = @import("embedded/webapp_assets.zig");

// The webview implementation is the vendored webview/webview library
// (vendor/webview/webview.{h,cc}), compiled as C++ by build.zig and
// linked into this binary. The extern "c" symbols (webview_create,
// webview_run, ...) are declared in webview_lib.zig and defined in the
// compiled library object — no platform/ import needed here anymore.
// build.zig is responsible for compiling vendor/webview/webview.cc and
// linking the GTK3/webkit2gtk-4.1 system libraries on Linux.

// Pull in the test files so they run under `zig build test:desktop-app`.
test {
    _ = @import("test_runner.zig");
}

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;
    // init.environ_map is used below (read PATH for attach.zig's auto-spawn).

    // 1. Parse CLI args. `init.minimal.args` is a `process.Args` iterator
    // in Zig 0.16 (not a slice), so we materialize it into an ArrayList.
    // Use `initAllocator` (NOT `init`) — `Args.Iterator.init` raises a
    // `@compileError` on Windows in Zig 0.16: "In Windows, use
    // initAllocator instead." `initAllocator` works on every platform.
    var args_buf: std.ArrayList([]const u8) = .empty;
    defer args_buf.deinit(allocator);
    var args_iter = try std.process.Args.Iterator.initAllocator(init.minimal.args, allocator);
    defer args_iter.deinit();
    while (args_iter.next()) |arg| {
        try args_buf.append(allocator, arg);
    }

    var cfg = cli.parse(allocator, args_buf.items) catch |err| switch (err) {
        error.ShowHelp => return,
        else => {
            std.log.err("Failed to parse CLI args: {s}", .{@errorName(err)});
            return err;
        },
    };
    defer cfg.deinit(allocator);

    // Headless smoke test (Chunk 2.1): bypass both spawn and webview paths
    // entirely. WebKitGTK cannot initialise without a display server, so the
    // best we can do on a CI runner is verify the binary loads, parses CLI,
    // extracts webapp assets to a temp dir, and exits 0 cleanly. CI invokes
    // this via `./zig-out/bin/nalar-desktop --smoke-test` after build.
    if (cfg.smoke_test) {
        const webapp_dir = extraction.extract(allocator, webapp_assets.assets) catch |err| {
            std.log.err("smoke: asset extraction failed: {s}", .{@errorName(err)});
            return err;
        };
        defer extraction.cleanup(allocator, webapp_dir);
        std.log.info("smoke: extracted {d} assets to {s}", .{ webapp_assets.assets.len, webapp_dir });
        return;
    }

    // 1b. Connect mode (--nalar-url): skip the entire spawn path. The
    // user has their own nalar running and we just point the webview at
    // it. --port and --nalar-path are ignored. Asset extraction is also
    // skipped (the external nalar is responsible for serving the webapp).
    if (cfg.nalar_url) |url| {
        std.log.info("Connect mode: connecting to {s} (no spawn)", .{url});
        try runWebview(allocator, cfg, url);
        return;
    }

    // SPAWN MODE was removed in the decoupled-nalar-service refactor.
    // The desktop now ONLY attaches to an already-running nalar (or
    // asks the user to start one). The new flow lives in the
    // "ATTACH MODE" block below.

    // ATTACH MODE (default + new behavior).
    //
    // 1. Extract the embedded webapp assets to a per-pid temp dir.
    //    Even if the user already has a nalar running, the desktop
    //    owns the webapp and we want the next auto-spawn to be able
    //    to serve it via `--static-dir`. If we end up attaching to
    //    an existing nalar (no auto-spawn), the extracted dir goes
    //    unused and is cleaned up at process exit.
    //
    //    NOTE: when the auto-spawn path fires, the spawned nalar
    //    outlives the desktop (architectural commitment: closing the
    //    window does NOT stop nalar). The temp dir becomes part of
    //    nalar's runtime state, so we LEAK the path on auto-spawn
    //    success — the OS will clean it up at next reboot. The leak
    //    is bounded (one dir per process) and the temp name includes
    //    the PID, so it's discoverable in `/tmp` if debugging is
    //    ever needed. A future improvement is to register the dir
    //    with a `nalar service register-static-dir <path>` call so
    //    the user can clean it up via `service stop`.
    const webapp_dir = extraction.extract(allocator, webapp_assets.assets) catch |err| {
        std.log.err("Failed to extract webapp assets to temp dir: {s}", .{@errorName(err)});
        return err;
    };
    defer extraction.cleanup(allocator, webapp_dir);



    // 2. Resolve the attach target via attach.zig: probe state file
    //    → health → connect. If nalar isn't running and --no-auto-start
    //    was passed, surface an actionable error.
    const state_path = nalarcore.state_file.defaultStatePath(allocator) catch |err| {
        std.log.err("Failed to resolve state.json path: {s}", .{@errorName(err)});
        return err;
    };
    defer allocator.free(state_path);

    // Resolve the desktop's own exe path for attach.zig's "next to self"
    // nalar lookup (auto-spawn path only). Best-effort: on platforms
    // without /proc/self/exe, fall back to "." and let the auto-spawn
    // path skip the "next to self" check.
    const self_exe_owned = path_resolve.selfExePath(allocator) catch ".";
    defer if (!std.mem.eql(u8, self_exe_owned, ".")) allocator.free(self_exe_owned);

    // PATH env (for the auto-spawn fallback when --nalar-path is unset
    // and nalar isn't next to the desktop binary).
    //
    // NOTE: `init.environ_map.get(key)` returns a `[]const u8` slice
    // that points into the Environ map's INTERNAL storage (a borrow,
    // not an owned allocation). We MUST NOT call `allocator.free` on
    // it — that's the double-free the smoke test caught. The `[]const u8`
    // has the same lifetime as `init.environ_map` (the entire process),
    // which is fine for our use.
    const path_env = init.environ_map.get("PATH") orelse "";

    const attach_target = attach.resolveAttachTarget(allocator, io, .{
        .state_path = state_path,
        .default_port = if (cfg.attach_port == 0) 8081 else cfg.attach_port,
        .no_auto_start = cfg.no_auto_start,
        .nalar_path = cfg.nalar_path,
        .self_exe_path = self_exe_owned,
        .path_env = path_env,
        .static_dir = webapp_dir,
    }) catch |err| switch (err) {
        error.AutoStartDisabled => {
            std.log.err("nalar is not running.", .{});
            std.log.err("Run `nalar service start` in a terminal first, then re-open the desktop.", .{});
            return err;
        },
        error.NalarNotFound => {
            // Already logged from attach.zig with hints; just exit cleanly.
            return err;
        },
        error.AutoSpawnFailed => {
            // Already logged from attach.zig with hints; just exit cleanly.
            return err;
        },
        else => return err,
    };
    defer allocator.free(attach_target.host);

    // 2. Build the URL.
    const url = try std.fmt.allocPrint(allocator, "http://{s}:{d}/", .{ attach_target.host, attach_target.port });
    defer allocator.free(url);

    // 3. Run the webview. No defer terminate — the desktop's lifetime
    //    is now decoupled from nalar's. Closing the window does NOT
    //    signal nalar; only `nalar service stop` does.
    std.log.info("Attaching to nalar at {s} (we_spawned={any})", .{ url, attach_target.we_spawned });
    try runWebview(allocator, cfg, url);
}

/// Open the webview window and run the platform event loop (blocks
/// until the window closes). Thin pass-through to the vendored
/// webview/webview library — everything the library does by default is
/// what ships (including its built-in WebKit DMA-BUF/NVIDIA
/// workaround and clipboard-access setting).
///
/// The backend serves the webapp over http://127.0.0.1:PORT, so no
/// custom scheme handler or embedded asset table is needed.
fn runWebview(
    allocator: std.mem.Allocator,
    cfg: cli.Config,
    url: []const u8,
) !void {
    // Null-terminate the strings the C ABI expects.
    const title_z = try allocator.dupeZ(u8, cfg.title);
    defer allocator.free(title_z);
    const url_z = try allocator.dupeZ(u8, url);
    defer allocator.free(url_z);

    std.log.info("Opening webview at {s}", .{url});
    webview_lib.runWindow(
        title_z.ptr,
        url_z.ptr,
        @intCast(cfg.window_width),
        @intCast(cfg.window_height),
        cfg.enable_devtools,
        cfg.force_x11,
    ) catch |err| {
        std.log.err("Webview error: {s}", .{@errorName(err)});
        return err;
    };
    std.log.info("Window closed. Exiting.", .{});
}
