// tools/codegen_webapp_assets.zig
//
// Comptime codegen: walk the Vue webapp's built dist/ tree and emit a Zig
// source file with the byte-for-byte contents of every asset embedded as
// string literals. The generated file (src/apps/desktop_app/embedded/
// webapp_assets.zig) is imported by main.zig (in a later chunk) and the
// `pub const assets: []const Asset` value it provides is what gets written
// to a per-user temp dir at runtime by extraction.zig.
//
// Usage (from the project root, after `zig build build:webapp`):
//
//     zig build codegen:webapp-assets
//
// The build step wires this up; you can also run the binary directly:
//
//     zig run tools/codegen_webapp_assets.zig -- \
//         src/apps/desktop/dist \
//         src/apps/desktop_app/embedded/webapp_assets.zig
//
// Zig 0.16 API notes:
//   * `std.heap.GeneralPurposeAllocator` was replaced by
//     `std.heap.DebugAllocator`; the codegen tool uses
//     `std.heap.page_allocator` instead since it's a one-shot CLI tool
//     that exits within a few hundred ms.
//   * `std.process.args()` is gone; args are delivered via
//     `std.process.Init.minimal.args` and consumed through
//     `std.process.Args.Iterator`.
//   * This file uses std.c.* (libc, cross-platform) for all filesystem
//     syscalls instead of std.os.linux.* so the binary runs on both
//     Linux and macOS CI cells. Std.c.faccessat / mkdir / open / close /
//     read / write / fstat / opendir / readdir / closedir all resolve
//     to libc via std.c, which dispatches to the right syscall per
//     platform at compile time.

const std = @import("std");
const builtin = @import("builtin");

pub fn main(init: std.process.Init) !void {
    // Codegen is a one-shot CLI tool: each invocation scans dist/ once and
    // writes one output file. Page allocator is fine here — no leak
    // concerns for a process that exits within a few hundred ms.
    const allocator = std.heap.page_allocator;

    // CLI args. The build.zig step invokes the binary with two positional
    // arguments: the dist/ root and the output .zig file path.
    var args_iter = try std.process.Args.Iterator.initAllocator(init.minimal.args, allocator);
    _ = args_iter.next() orelse return error.MissingExeName;
    const dist_path = args_iter.next() orelse return error.MissingDistPath;
    const out_path = args_iter.next() orelse return error.MissingOutPath;

    // Check if dist_path exists. If not, emit a stub webapp_assets.zig
    // (empty assets array) so the nalar-desktop build doesn't fail when
    // `bun run build` hasn't been run yet (e.g., on a fresh checkout).
    // Use std.c.access (POSIX, cross-platform via libc) instead of
    // std.os.linux.faccessat (Linux syscall only — would SIGSYS on macOS).
    var dist_path_buf: [8192:0]u8 = undefined;
    const dist_path_z = copyToNull(&dist_path_buf, dist_path);
    const acc_rc = std.c.access(dist_path_z, 0); // F_OK = 0
    const dist_exists = if (acc_rc == 0) true else blk: {
        const errno_val = std.c.errno(acc_rc);
        if (errno_val == .NOENT) break :blk false;
        return error.AccessFailed;
    };
    if (!dist_exists) {
        std.debug.print("warning: {s} not found; emitting empty webapp_assets.zig stub. Run 'bun run build' in the webapp dir to populate.\n", .{dist_path});
    }

    // Walk the dist/ tree and collect every file's path (relative to
    // the root, with forward slashes — the walker normalizes them).
    var files: std.ArrayList([]const u8) = .empty;
    defer files.deinit(allocator);
    if (dist_exists) {
        try walkDir(allocator, dist_path, "", &files);
    }

    // Deterministic output order: sort lexicographically.
    std.mem.sort([]const u8, files.items, {}, lessThan);

    // Accumulate the generated Zig source in a heap ArrayList. The
    // dist/ is ~4.5 MiB, the generated source is ~10 MiB after hex
    // escaping.
    var out_buf: std.ArrayList(u8) = .empty;
    defer out_buf.deinit(allocator);

    // Header — the generated file's public surface. Keep this stable;
    // the extraction.zig code imports `webapp_assets.assets` and treats
    // each `Asset` as a `{ path, content, mime }` triple.
    try out_buf.appendSlice(allocator,
        \\// GENERATED by tools/codegen_webapp_assets.zig — DO NOT EDIT
        \\// To regenerate: zig build codegen:webapp-assets
        \\
        \\const std = @import("std");
        \\
        \\pub const Asset = struct {
        \\    /// Path as served by the webserver, e.g. "/assets/index-abc.js"
        \\    path: []const u8,
        \\    /// File contents (use as-is; do not modify).
        \\    content: []const u8,
        \\    /// Inferred MIME type with charset for text/* types.
        \\    mime: []const u8,
        \\};
        \\
    );

    try out_buf.appendSlice(allocator, "pub const assets: []const Asset = &.{\n");

    for (files.items) |rel| {
        const abs = try std.fs.path.join(allocator, &.{ dist_path, rel });
        defer allocator.free(abs);
        const content = try readFileAll(allocator, abs, 10 * 1024 * 1024);
        defer allocator.free(content);
        const path_served = try std.fmt.allocPrint(allocator, "/{s}", .{rel});
        defer allocator.free(path_served);
        const mime = inferMime(rel);

        const header_line = try std.fmt.allocPrint(
            allocator,
            "    .{{ .path = \"{s}\", .content = \"",
            .{path_served},
        );
        defer allocator.free(header_line);
        try out_buf.appendSlice(allocator, header_line);

        for (content) |b| {
            switch (b) {
                0...8, 11, 12, 14...31 => {
                    var esc: [4]u8 = undefined;
                    _ = std.fmt.bufPrint(&esc, "\\x{x:0>2}", .{b}) catch unreachable;
                    try out_buf.appendSlice(allocator, &esc);
                },
                32...33, 35...91, 93...126 => try out_buf.append(allocator, b),
                '"', '\\' => {
                    var esc: [2]u8 = .{ '\\', b };
                    try out_buf.appendSlice(allocator, &esc);
                },
                else => {
                    var esc: [4]u8 = undefined;
                    _ = std.fmt.bufPrint(&esc, "\\x{x:0>2}", .{b}) catch unreachable;
                    try out_buf.appendSlice(allocator, &esc);
                },
            }
        }

        const footer_line = try std.fmt.allocPrint(allocator, "\", .mime = \"{s}\" }},\n", .{mime});
        defer allocator.free(footer_line);
        try out_buf.appendSlice(allocator, footer_line);
    }

    try out_buf.appendSlice(allocator, "};\n");

    // Open the output file. The parent dir is created if missing so the
    // step works on a fresh checkout with no `embedded/` dir.
    const out_dir_path = std.fs.path.dirname(out_path) orelse ".";
    const out_basename = std.fs.path.basename(out_path);
    try mkdirsRecursive(out_dir_path);
    const out_fd = try openCreateTrunc(out_dir_path, out_basename);
    defer _ = std.c.close(out_fd);

    // Dump the accumulated buffer with a single raw write(2) syscall.
    var written: usize = 0;
    while (written < out_buf.items.len) {
        const n_rc = std.c.write(out_fd, out_buf.items[written..].ptr, out_buf.items.len - written);
        if (n_rc < 0) return error.WriteFailed;
        const n: usize = @intCast(n_rc);
        if (n == 0) return error.WriteFailed;
        written += n;
    }

    if (dist_exists) {
        std.debug.print("Generated {s} with {d} assets\n", .{ out_path, files.items.len });
    } else {
        std.debug.print("Generated {s} with 0 assets (stub: dist/ was not found; run 'bun run build' to populate)\n", .{out_path});
    }
}

fn lessThan(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, a, b);
}

/// Recursively walk a directory tree using POSIX `opendir/readdir` and
/// append every regular file's path (relative to `root`) to `out`.
/// Directories are recursed; symlinks are skipped to avoid cycles.
fn walkDir(
    allocator: std.mem.Allocator,
    root: []const u8,
    prefix: []const u8,
    out: *std.ArrayList([]const u8),
) !void {
    const full_dir = if (prefix.len == 0)
        try allocator.dupe(u8, root)
    else
        try std.fs.path.join(allocator, &.{ root, prefix });
    defer allocator.free(full_dir);

    var open_path_buf: [8192:0]u8 = undefined;
    const open_path = copyToNull(&open_path_buf, full_dir);
    const dir_ptr = std.c.opendir(open_path) orelse return error.OpenDirFailed;
    defer _ = std.c.closedir(dir_ptr);

    // Iterate directory entries via POSIX readdir. The `dirent` struct
    // differs between Linux and macOS in Zig 0.16's std.c binding (Linux
    // has `name: [256]u8` + `reclen`, Apple has `name: [1024]u8` +
    // `namlen`), so we read just enough fields to get the name and the
    // entry type. Both variants expose `type` (a u8 holding the DT_*
    // value) so the DIR/REG switch below works on either.
    while (std.c.readdir(dir_ptr)) |raw_entry| {
        const entry: *std.c.dirent = raw_entry;

        // Get the NUL-terminated name as a slice. std.c.dirent is a
        // comptime-shaped extern struct whose `name` field is a fixed
        // buffer; sliceTo works regardless of which platform's struct
        // we're looking at because the name is always NUL-terminated
        // by the kernel.
        const name = std.mem.sliceTo(&entry.name, 0);

        // Skip "." and "..".
        if (name.len > 0 and !(name.len == 1 and name[0] == '.') and
            !(name.len == 2 and name[0] == '.' and name[1] == '.'))
        {
            const rel = try std.fs.path.join(allocator, &.{ prefix, name });

            // DT_REG = 8 on Linux, DT_DIR = 4 on Linux; both are the same
            // numeric values on macOS (kqueue/Berkeley-derived constants).
            // Using std.c.DT.REG / DT.DIR via comptime ensures correct
            // values per platform.
            if (entry.type == comptime dtValue(.REG)) {
                try out.append(allocator, rel);
            } else if (entry.type == comptime dtValue(.DIR)) {
                try walkDir(allocator, root, rel, out);
            } else {
                allocator.free(rel); // symlinks etc. — skip
            }
        }
    }
}

/// Return the integer `DT_*` value for `kind` (REG | DIR) on the current
/// platform. DT_REG and DT_DIR are values inside `<dirent.h>` and are
/// stable across Linux/macOS (both descend from BSD), so we just match by
/// name. Computed at comptime.
fn dtValue(comptime kind: enum { REG, DIR }) u8 {
    return switch (kind) {
        .REG => 8, // DT_REG
        .DIR => 4, // DT_DIR
    };
}

/// Copy a path into a caller-provided NUL-terminated stack buffer and
/// return a pointer to the start. The caller must keep `buf` alive for
/// the lifetime of the returned pointer (so the buffer must be in the
/// caller's stack frame, not a separate function).
fn copyToNull(buf: *[8192:0]u8, path: []const u8) [*:0]const u8 {
    if (path.len >= buf.len) @panic("path too long for null-terminated buffer");
    @memcpy(buf[0..path.len], path);
    buf[path.len] = 0;
    return buf;
}

/// `mkdir(2)` the given path, creating any missing parents.
fn mkdirsRecursive(path: []const u8) !void {
    if (path.len == 0 or (path.len == 1 and path[0] == '.')) return;

    var path_buf: [8192:0]u8 = undefined;
    const path_z = copyToNull(&path_buf, path);

    // If it already exists, we're done. std.c.access returns 0 on
    // success, -1 on failure (errno set to EEXIST or similar).
    if (std.c.access(path_z, 0) == 0) return;

    // Recurse on the parent first.
    if (std.fs.path.dirname(path)) |parent| {
        if (parent.len < path.len) try mkdirsRecursive(parent);
    }

    // Now mkdir this path. std.c.mkdir returns 0 on success, -1 on
    // failure with errno set. EEXIST is fine (a concurrent creator).
    if (std.c.mkdir(path_z, @as(std.c.mode_t, 0o755)) != 0) {
        const errno_val = std.c.errno(-1);
        if (errno_val != .EXIST) return error.MkdirFailed;
    }
}

/// Open (or create + truncate) a file for writing. Returns the raw fd.
fn openCreateTrunc(dir_path: []const u8, basename: []const u8) !std.c.fd_t {
    const flags: std.c.O = .{
        .ACCMODE = .WRONLY,
        .CREAT = true,
        .TRUNC = true,
        .CLOEXEC = true,
    };
    const full = try std.fs.path.join(std.heap.page_allocator, &.{ dir_path, basename });
    defer std.heap.page_allocator.free(full);

    var open_path_buf: [8192:0]u8 = undefined;
    const open_path = copyToNull(&open_path_buf, full);

    const rc = std.c.open(open_path, flags, @as(std.c.mode_t, 0o644));
    if (rc < 0) return error.OpenOutFailed;
    return rc;
}

/// Read the entire contents of a file into a fresh allocation. Returns
/// the buffer; caller owns it. A safety cap of `max_bytes` is enforced
/// Read the entire contents of a file into a fresh allocation. Returns
/// the buffer; caller owns it. A safety cap of `max_bytes` is enforced
/// to catch runaway inputs. We don't call fstat (Zig 0.16 has no
/// cross-platform fstat — std.c.fstat is `void` on Linux and the stdlib
/// recommends statx instead). Instead, we read incrementally into a
/// growing ArrayList, doubling the read buffer each round and stopping
/// at EOF. Works on every platform the build tool runs on.
fn readFileAll(allocator: std.mem.Allocator, path: []const u8, max_bytes: usize) ![]u8 {
    var path_buf: [8192:0]u8 = undefined;
    const path_z = copyToNull(&path_buf, path);

    const fd_rc = std.c.open(path_z, .{ .ACCMODE = .RDONLY, .CLOEXEC = true }, @as(std.c.mode_t, 0));
    if (fd_rc < 0) return error.OpenFileFailed;
    const fd: std.c.fd_t = fd_rc;
    defer _ = std.c.close(fd);

    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(allocator);
    try buf.ensureTotalCapacity(allocator, 4 * 1024);
    var total: usize = 0;
    var chunk: [64 * 1024]u8 = undefined;
    while (true) {
        const n_rc = std.c.read(fd, &chunk, chunk.len);
        if (n_rc < 0) return error.ReadFailed;
        const n: usize = @intCast(n_rc);
        if (n == 0) break; // EOF
        if (total + n > max_bytes) return error.FileTooLarge;
        try buf.appendSlice(allocator, chunk[0..n]);
        total += n;
    }
    return buf.toOwnedSlice(allocator);
}

/// MIME type lookup by file extension.
fn inferMime(path: []const u8) []const u8 {
    if (std.mem.endsWith(u8, path, ".html")) return "text/html; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".css")) return "text/css; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".js")) return "application/javascript; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".mjs")) return "application/javascript; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".json")) return "application/json; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".svg")) return "image/svg+xml";
    if (std.mem.endsWith(u8, path, ".png")) return "image/png";
    if (std.mem.endsWith(u8, path, ".jpg") or std.mem.endsWith(u8, path, ".jpeg")) return "image/jpeg";
    if (std.mem.endsWith(u8, path, ".gif")) return "image/gif";
    if (std.mem.endsWith(u8, path, ".webp")) return "image/webp";
    if (std.mem.endsWith(u8, path, ".ico")) return "image/x-icon";
    if (std.mem.endsWith(u8, path, ".woff")) return "font/woff";
    if (std.mem.endsWith(u8, path, ".woff2")) return "font/woff2";
    if (std.mem.endsWith(u8, path, ".ttf")) return "font/ttf";
    if (std.mem.endsWith(u8, path, ".map")) return "application/json; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".txt")) return "text/plain; charset=utf-8";
    return "application/octet-stream";
}
