// tools/codegen_webapp_assets.zig
//
// Comptime codegen: walk the Vue webapp's built dist/ tree and emit a Zig
// source file with the byte-for-byte contents of every asset embedded as
// string literals. The generated file (src/apps/desktop_app/embedded/
// webapp_assets.zig) is imported by main.zig (in a later chunk) and the
// `pub const assets: []const Asset` value it provides is what gets written
// to a per-user temp dir at runtime by extraction.zig.
//
// Usage (from the project root, after `zig build build:webapp`):
//
//     zig build codegen:webapp-assets
//
// The build step wires this up; you can also run the binary directly:
//
//     zig run tools/codegen_webapp_assets.zig -- \
//         src/apps/desktop/dist \
//         src/apps/desktop_app/embedded/webapp_assets.zig
//
// Zig 0.16 API notes:
//   * `std.heap.GeneralPurposeAllocator` was replaced by
//     `std.heap.DebugAllocator`; the codegen tool uses
//     `std.heap.page_allocator` instead since it's a one-shot CLI tool
//     that exits within a few hundred ms.
//   * `std.process.args()` is gone; args are delivered via
//     `std.process.Init.minimal.args` and consumed through
//     `std.process.Args.Iterator`.
//   * `std.fs.cwd()` and the old `std.fs.File.writer()` are gone in 0.16;
//     a writer-based output flow now needs an `Io` runtime and a buffer.
//     For a build tool, the simpler approach is to accumulate bytes in
//     a heap `ArrayList(u8)` and dump it with a single raw `write(2)`
//     syscall. This matches the syscall-based patterns already used in
//     subprocess.zig / path_resolve.zig / subprocess_test.zig.

const std = @import("std");

pub fn main(init: std.process.Init) !void {
    // Codegen is a one-shot CLI tool: each invocation scans dist/ once and
    // writes one output file. Page allocator is fine here — no leak
    // concerns for a process that exits within a few hundred ms. If
    // someone wants to keep it under -D LeakSanitizer-style debug later,
    // swap to `std.heap.DebugAllocator(.{})` (Zig 0.16 replaced the old
    // `GeneralPurposeAllocator` with `DebugAllocator`).
    const allocator = std.heap.page_allocator;

    // CLI args. The build.zig step invokes the binary with two positional
    // arguments: the dist/ root and the output .zig file path. Zig 0.16
    // dropped the global `std.process.args()`; args are now delivered via
    // `std.process.Init.minimal.args` and consumed through the new
    // `std.process.Args.Iterator` (which yields each argv as a `[]u8`
    // slice borrowed from the OS — safe for the lifetime of the process).
    var args_iter = std.process.Args.Iterator.init(init.minimal.args);
    _ = args_iter.next() orelse return error.MissingExeName;
    const dist_path = args_iter.next() orelse return error.MissingDistPath;
    const out_path = args_iter.next() orelse return error.MissingOutPath;

    // Walk the dist/ tree and collect every file's path (relative to the
    // root, with forward slashes — the walker normalizes them).
    var files: std.ArrayList([]const u8) = .empty;
    defer files.deinit(allocator);
    try walkDir(allocator, dist_path, "", &files);

    // Deterministic output order: sort lexicographically. Without this the
    // generated file would change order across runs (the walk order is
    // inode-dependent on most filesystems), which would dirty the Zig
    // build cache unnecessarily.
    std.mem.sort([]const u8, files.items, {}, lessThan);

    // Accumulate the generated Zig source in a heap ArrayList. The dist/
    // is ~4.5 MiB, the generated source is ~10 MiB after hex escaping.
    var out_buf: std.ArrayList(u8) = .empty;
    defer out_buf.deinit(allocator);

    // Header — the generated file's public surface. Keep this stable; the
    // extraction.zig code in this chunk imports `webapp_assets.assets`
    // and treats each `Asset` as a `{ path, content, mime }` triple.
    try out_buf.appendSlice(allocator,
        \\// GENERATED by tools/codegen_webapp_assets.zig — DO NOT EDIT
        \\// To regenerate: zig build codegen:webapp-assets
        \\
        \\const std = @import("std");
        \\
        \\pub const Asset = struct {
        \\    /// Path as served by the webserver, e.g. "/assets/index-abc.js"
        \\    path: []const u8,
        \\    /// File contents (use as-is; do not modify).
        \\    content: []const u8,
        \\    /// Inferred MIME type with charset for text/* types.
        \\    mime: []const u8,
        \\};
        \\
    );

    try out_buf.appendSlice(allocator, "pub const assets: []const Asset = &.{\n");

    // Per-asset entry. We embed the content as a Zig string literal with
    // explicit escapes for the few control bytes that would otherwise
    // close the literal. Binary content (images, fonts) is hex-escaped
    // one byte at a time. A 10 MiB safety cap is plenty for the Vue
    // webapp's dist/ output (in practice the largest file is the JS
    // bundle, ~1 MiB).
    for (files.items) |rel| {
        const abs = try std.fs.path.join(allocator, &.{ dist_path, rel });
        defer allocator.free(abs);
        const content = try readFileAll(allocator, abs, 10 * 1024 * 1024);
        defer allocator.free(content);
        const path_served = try std.fmt.allocPrint(allocator, "/{s}", .{rel});
        defer allocator.free(path_served);
        const mime = inferMime(rel);

        const header_line = try std.fmt.allocPrint(
            allocator,
            "    .{{ .path = \"{s}\", .content = \"",
            .{path_served},
        );
        defer allocator.free(header_line);
        try out_buf.appendSlice(allocator, header_line);

        for (content) |b| {
            // Escape bytes that would break a Zig string literal. The
            // control ranges (0..7, 11, 12, 14..31) and the high bytes
            // (128..255) are emitted as \xNN so the literal stays valid
            // Zig source regardless of the asset's actual bytes.
            switch (b) {
                // Printable ASCII that needs no escape: digit, letter,
                // space, common punctuation. Note: '"' (34) and '\\' (92)
                // are inside 32...126 but they MUST be escaped, so we
                // special-case them first; the `else` below catches
                // everything else in the printable range.
                0...8, 11, 12, 14...31 => {
                    var esc: [4]u8 = undefined;
                    _ = std.fmt.bufPrint(&esc, "\\x{x:0>2}", .{b}) catch unreachable;
                    try out_buf.appendSlice(allocator, &esc);
                },
                32...33, 35...91, 93...126 => try out_buf.append(allocator, b),
                '"', '\\' => {
                    // Two-character escape ("\"" or "\\").
                    var esc: [2]u8 = .{ '\\', b };
                    try out_buf.appendSlice(allocator, &esc);
                },
                else => {
                    var esc: [4]u8 = undefined;
                    _ = std.fmt.bufPrint(&esc, "\\x{x:0>2}", .{b}) catch unreachable;
                    try out_buf.appendSlice(allocator, &esc);
                },
            }
        }

        const footer_line = try std.fmt.allocPrint(allocator, "\", .mime = \"{s}\" }},\n", .{mime});
        defer allocator.free(footer_line);
        try out_buf.appendSlice(allocator, footer_line);
    }

    try out_buf.appendSlice(allocator, "};\n");

    // Open the output file. The parent dir is created if missing so the
    // step works on a fresh checkout with no `embedded/` dir.
    const out_dir_path = std.fs.path.dirname(out_path) orelse ".";
    const out_basename = std.fs.path.basename(out_path);
    try mkdirsRecursive(out_dir_path);
    const out_fd = try openCreateTrunc(out_dir_path, out_basename);
    defer _ = std.os.linux.close(out_fd);

    // Dump the accumulated buffer with a single raw write(2) syscall. The
    // Zig 0.16 stdlib no longer exposes a fd-based Writer for raw fds
    // (the Io-based writer requires an Io runtime), so we just call the
    // syscall directly. If the buffer is larger than the kernel's max
    // single-write size (typically 2 GiB on Linux) we'd need to loop,
    // but our generated file is well under that.
    var written: usize = 0;
    while (written < out_buf.items.len) {
        const n_rc = std.os.linux.write(out_fd, out_buf.items[written..].ptr, out_buf.items.len - written);
        if (n_rc > std.math.maxInt(usize)) return error.WriteFailed;
        const n: usize = @intCast(n_rc);
        if (n == 0) return error.WriteFailed;
        written += n;
    }

    std.debug.print("Generated {s} with {d} assets\n", .{ out_path, files.items.len });
}

fn lessThan(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, a, b);
}

/// Recursively walk a directory tree using raw `getdents64(2)` and append
/// every regular file's path (relative to `root`) to `out`. Directories
/// are recursed; symlinks are skipped to avoid cycles.
fn walkDir(
    allocator: std.mem.Allocator,
    root: []const u8,
    prefix: []const u8,
    out: *std.ArrayList([]const u8),
) !void {
    const full_dir = if (prefix.len == 0)
        try allocator.dupe(u8, root)
    else
        try std.fs.path.join(allocator, &.{ root, prefix });
    defer allocator.free(full_dir);

    // O_DIRECTORY | O_RDONLY = open the path as a directory fd.
    // O_CLOEXEC so we don't leak the fd into a child process (defensive;
    // this tool doesn't fork).
    var open_path_buf: [8192:0]u8 = undefined;
    const open_path = copyToNull(&open_path_buf, full_dir);
    const dir_fd = std.os.linux.open(
        open_path,
        .{ .ACCMODE = .RDONLY, .DIRECTORY = true, .CLOEXEC = true },
        0,
    );
    if (dir_fd > std.math.maxInt(i32)) return error.OpenDirFailed;
    const fd: i32 = @intCast(dir_fd);
    defer _ = std.os.linux.close(fd);

    // Iterate the directory entries. getdents64 returns one or more
    // `std.os.linux.dirent64` structs in a buffer; we advance by
    // `entry.reclen` until the syscall returns 0 (end of dir). The 0.16
    // stdlib's getdents64 takes only (fd, buf, len) — no offset
    // argument, so we just call it in a loop until the kernel returns 0.
    //
    // The dirent64 struct in 0.16 is `{ ino, off, reclen, type, name: [0]u8 }`
    // — `name` is a zero-length array, so the actual filename bytes
    // start at the address of `entry.name[0]` and run up to a NUL byte
    // (or to `entry.reclen` bytes, whichever comes first).
    var buf: [4096]u8 align(@alignOf(std.os.linux.dirent64)) = undefined;
    while (true) {
        const n_rc = std.os.linux.getdents64(fd, &buf, buf.len);
        if (n_rc > std.math.maxInt(usize)) return error.GetDentsFailed;
        const n: usize = @intCast(n_rc);
        if (n == 0) break;

        var pos: usize = 0;
        while (pos < n) {
            const entry: *align(1) const std.os.linux.dirent64 = @ptrCast(&buf[pos]);
            const name_ptr: [*]const u8 = &entry.name;
            // The name is NUL-terminated; std.mem.sliceTo finds the end.
            // The `name` field is at offset 19 inside dirent64 (NOT at
            // the struct's `@sizeOf` which is 24 due to padding), so use
            // `@offsetOf("name")` rather than `@sizeOf` for the start.
            // The kernel pads the total entry to 8-byte alignment, so
            // `reclen` is the upper bound for the name.
            const reclen_usize: usize = @as(usize, @intCast(entry.reclen));
            const name_offset: usize = @offsetOf(std.os.linux.dirent64, "name");
            const name_max_len: usize = reclen_usize - name_offset;
            const name = std.mem.sliceTo(name_ptr[0..name_max_len], 0);

            // Skip "." and "..".
            if (name.len > 0 and !(name.len == 1 and name[0] == '.') and
                !(name.len == 2 and name[0] == '.' and name[1] == '.'))
            {
                const rel = try std.fs.path.join(allocator, &.{ prefix, name });

                switch (entry.type) {
                    std.os.linux.DT.REG => try out.append(allocator, rel),
                    std.os.linux.DT.DIR => try walkDir(allocator, root, rel, out),
                    else => allocator.free(rel), // symlinks etc. — skip
                }
            }

            pos += entry.reclen;
        }
    }
}

/// Copy a path into a caller-provided NUL-terminated stack buffer and
/// return a pointer to the start. The caller must keep `buf` alive for
/// the lifetime of the returned pointer (so the buffer must be in the
/// caller's stack frame, not a separate function — see NALAR.md's
/// "Never return stack-allocated slices from functions" note).
fn copyToNull(buf: *[8192:0]u8, path: []const u8) [*:0]const u8 {
    if (path.len >= buf.len) @panic("path too long for null-terminated buffer");
    @memcpy(buf[0..path.len], path);
    buf[path.len] = 0;
    return buf;
}

/// `mkdir(2)` the given path, creating any missing parents. Mirrors the
/// behaviour of `mkdir -p`.
fn mkdirsRecursive(path: []const u8) !void {
    if (path.len == 0 or (path.len == 1 and path[0] == '.')) return;

    // Open a per-call null-terminated buffer; can't be a helper return
    // (see NALAR.md note on stack-allocated slices).
    var path_buf: [8192:0]u8 = undefined;
    const path_z = copyToNull(&path_buf, path);

    // If it already exists, we're done.
    const acc_rc = std.os.linux.faccessat(std.os.linux.AT.FDCWD, path_z, 0, 0);
    if (acc_rc == 0) return;

    // Recurse on the parent first.
    if (std.fs.path.dirname(path)) |parent| {
        if (parent.len < path.len) try mkdirsRecursive(parent);
    }

    // Now mkdir this path. EEXIST is fine (a concurrent creator).
    // The Zig 0.16 `std.os.linux.mkdir` returns `usize`; on failure the
    // value is `-errno` (cast to usize via two's-complement bitcast).
    // We negate back to `isize` and compare against the EEXIST errno
    // number (17) via @intFromEnum.
    const rc = std.os.linux.mkdir(path_z, 0o755);
    if (rc != 0) {
        const rc_signed: isize = @bitCast(rc);
        const errno: usize = @intCast(-rc_signed);
        if (errno == @intFromEnum(std.os.linux.E.EXIST)) return;
        return error.MkdirFailed;
    }
}

/// Open (or create + truncate) a file for writing. Returns the raw fd.
fn openCreateTrunc(dir_path: []const u8, basename: []const u8) !i32 {
    // O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC
    const flags: std.os.linux.O = .{
        .ACCMODE = .WRONLY,
        .CREAT = true,
        .TRUNC = true,
        .CLOEXEC = true,
    };
    const full = try std.fs.path.join(std.heap.page_allocator, &.{ dir_path, basename });
    defer std.heap.page_allocator.free(full);

    var open_path_buf: [8192:0]u8 = undefined;
    const open_path = copyToNull(&open_path_buf, full);

    const rc = std.os.linux.open(open_path, flags, 0o644);
    if (rc > std.math.maxInt(i32)) return error.OpenOutFailed;
    return @intCast(rc);
}

/// Read the entire contents of a file into a fresh allocation. Returns
/// the buffer; caller owns it. A safety cap of `max_bytes` is enforced to
/// catch runaway inputs.
fn readFileAll(allocator: std.mem.Allocator, path: []const u8, max_bytes: usize) ![]u8 {
    var path_buf: [8192:0]u8 = undefined;
    const path_z = copyToNull(&path_buf, path);

    // Use statx(2) to get the file size. The old stat(2) wrapper was
    // removed from std.os.linux in 0.16 in favour of the newer
    // statx (which gives the same `size` field but with a more
    // flexible API and field-mask model). We only need `size`, but
    // ask for TYPE too so the syscall is meaningful.
    var statbuf: std.os.linux.Statx = undefined;
    const stat_rc = std.os.linux.statx(
        std.os.linux.AT.FDCWD,
        path_z,
        0,
        .{ .TYPE = true, .SIZE = true },
        &statbuf,
    );
    if (stat_rc != 0) return error.StatFailed;
    const size: usize = @intCast(statbuf.size);
    if (size > max_bytes) return error.FileTooLarge;

    const fd_rc = std.os.linux.open(path_z, .{ .ACCMODE = .RDONLY, .CLOEXEC = true }, 0);
    if (fd_rc > std.math.maxInt(i32)) return error.OpenFileFailed;
    const fd: i32 = @intCast(fd_rc);
    defer _ = std.os.linux.close(fd);

    const buf = try allocator.alloc(u8, size);
    var read_total: usize = 0;
    while (read_total < size) {
        const n_rc = std.os.linux.read(fd, buf[read_total..].ptr, size - read_total);
        if (n_rc > std.math.maxInt(usize)) return error.ReadFailed;
        const n: usize = @intCast(n_rc);
        if (n == 0) break; // EOF
        read_total += n;
    }
    return buf[0..read_total];
}

/// MIME type lookup by file extension. Mirrors the table in
/// src/modules/static_files.zig (kept in sync with the nalar server's
/// static-file serving logic) so the desktop app and the embedded nalar
/// agree on content-types for the same paths.
fn inferMime(path: []const u8) []const u8 {
    if (std.mem.endsWith(u8, path, ".html")) return "text/html; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".css")) return "text/css; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".js")) return "application/javascript; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".mjs")) return "application/javascript; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".json")) return "application/json; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".svg")) return "image/svg+xml";
    if (std.mem.endsWith(u8, path, ".png")) return "image/png";
    if (std.mem.endsWith(u8, path, ".jpg") or std.mem.endsWith(u8, path, ".jpeg")) return "image/jpeg";
    if (std.mem.endsWith(u8, path, ".gif")) return "image/gif";
    if (std.mem.endsWith(u8, path, ".webp")) return "image/webp";
    if (std.mem.endsWith(u8, path, ".ico")) return "image/x-icon";
    if (std.mem.endsWith(u8, path, ".woff")) return "font/woff";
    if (std.mem.endsWith(u8, path, ".woff2")) return "font/woff2";
    if (std.mem.endsWith(u8, path, ".ttf")) return "font/ttf";
    if (std.mem.endsWith(u8, path, ".map")) return "application/json; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".txt")) return "text/plain; charset=utf-8";
    return "application/octet-stream";
}
