// tools/codegen_webapp_assets.zig
//
// Comptime codegen: walk the Vue webapp's built dist/ tree and emit a Zig
// source file with the byte-for-byte contents of every asset embedded as
// string literals. The generated file (src/apps/desktop_app/embedded/
// webapp_assets.zig) is imported by main.zig (in a later chunk) and the
// `pub const assets: []const Asset` value it provides is what gets written
// to a per-user temp dir at runtime by extraction.zig.
//
// Usage (from the project root, after `zig build build:webapp`):
//
//     zig build codegen:webapp-assets
//
// The build step wires this up; you can also run the binary directly:
//
//     zig run tools/codegen_webapp_assets.zig -- \
//         src/apps/desktop/dist \
//         src/apps/desktop_app/embedded/webapp_assets.zig
//
// Zig 0.16 API notes:
//   * `std.heap.GeneralPurposeAllocator` was replaced by
//     `std.heap.DebugAllocator`; the codegen tool uses
//     `std.heap.page_allocator` instead since it's a one-shot CLI tool
//     that exits within a few hundred ms.
//   * `std.process.args()` is gone; args are delivered via
//     `std.process.Init.minimal.args` and consumed through
//     `std.process.Args.Iterator`.
//   * This file uses std.c.* (libc, cross-platform) for all filesystem
//     syscalls instead of std.os.linux.* so the binary runs on both
//     Linux and macOS CI cells. Std.c.faccessat / mkdir / open / close /
//     read / write / fstat / opendir / readdir / closedir all resolve
//     to libc via std.c, which dispatches to the right syscall per
//     platform at compile time.

const std = @import("std");
const builtin = @import("builtin");

pub fn main(init: std.process.Init) !void {
    // Codegen is a one-shot CLI tool: each invocation scans dist/ once and
    // writes one output file. Page allocator is fine here — no leak
    // concerns for a process that exits within a few hundred ms.
    const allocator = std.heap.page_allocator;

    // CLI args. The build.zig step invokes the binary with two positional
    // arguments: the dist/ root and the output .zig file path.
    var args_iter = try std.process.Args.Iterator.initAllocator(init.minimal.args, allocator);
    _ = args_iter.next() orelse return error.MissingExeName;
    const dist_path = args_iter.next() orelse return error.MissingDistPath;
    const out_path = args_iter.next() orelse return error.MissingOutPath;

    // Check if dist_path exists. If not, emit a stub webapp_assets.zig
    // (empty assets array) so the nalar-desktop build doesn't fail when
    // `bun run build` hasn't been run yet (e.g., on a fresh checkout).
    // Use std.c.access (POSIX, cross-platform via libc) instead of
    // std.os.linux.faccessat (Linux syscall only — would SIGSYS on macOS).
    var dist_path_buf: [8192:0]u8 = undefined;
    const dist_path_z = copyToNull(&dist_path_buf, dist_path);
    const acc_rc = std.c.access(dist_path_z, 0); // F_OK = 0
    const dist_exists = if (acc_rc == 0) true else blk: {
        const errno_val = std.c.errno(acc_rc);
        if (errno_val == .NOENT) break :blk false;
        return error.AccessFailed;
    };
    if (!dist_exists) {
        std.debug.print("warning: {s} not found; emitting empty webapp_assets.zig stub. Run 'bun run build' in the webapp dir to populate.\n", .{dist_path});
    }

    // Walk the dist/ tree and collect every file's path (relative to
    // the root, with forward slashes — the walker normalizes them).
    var files: std.ArrayList([]const u8) = .empty;
    defer files.deinit(allocator);
    if (dist_exists) {
        try walkDir(allocator, dist_path, "", &files);
    }

    // Deterministic output order: sort lexicographically.
    std.mem.sort([]const u8, files.items, {}, lessThan);

    // Accumulate the generated Zig source in a heap ArrayList. The
    // dist/ is ~4.5 MiB, the generated source is ~10 MiB after hex
    // escaping.
    var out_buf: std.ArrayList(u8) = .empty;
    defer out_buf.deinit(allocator);

    // Header — the generated file's public surface. Keep this stable;
    // the extraction.zig code imports `webapp_assets.assets` and treats
    // each `Asset` as a `{ path, content, mime }` triple.
    try out_buf.appendSlice(allocator,
        \\// GENERATED by tools/codegen_webapp_assets.zig — DO NOT EDIT
        \\// To regenerate: zig build codegen:webapp-assets
        \\
        \\const std = @import("std");
        \\
        \\pub const Asset = struct {
        \\    /// Path as served by the webserver, e.g. "/assets/index-abc.js"
        \\    path: []const u8,
        \\    /// File contents (use as-is; do not modify).
        \\    content: []const u8,
        \\    /// Inferred MIME type with charset for text/* types.
        \\    mime: []const u8,
        \\};
        \\
    );

    try out_buf.appendSlice(allocator, "pub const assets: []const Asset = &.{\n");

    for (files.items) |rel| {
        const abs = try std.fs.path.join(allocator, &.{ dist_path, rel });
        defer allocator.free(abs);
        const content = try readFileAll(allocator, abs, 10 * 1024 * 1024);
        defer allocator.free(content);
        const path_served = try std.fmt.allocPrint(allocator, "/{s}", .{rel});
        defer allocator.free(path_served);
        const mime = inferMime(rel);

        const header_line = try std.fmt.allocPrint(
            allocator,
            "    .{{ .path = \"{s}\", .content = \"",
            .{path_served},
        );
        defer allocator.free(header_line);
        try out_buf.appendSlice(allocator, header_line);

        for (content) |b| {
            switch (b) {
                0...8, 11, 12, 14...31 => {
                    var esc: [4]u8 = undefined;
                    _ = std.fmt.bufPrint(&esc, "\\x{x:0>2}", .{b}) catch unreachable;
                    try out_buf.appendSlice(allocator, &esc);
                },
                32...33, 35...91, 93...126 => try out_buf.append(allocator, b),
                '"', '\\' => {
                    var esc: [2]u8 = .{ '\\', b };
                    try out_buf.appendSlice(allocator, &esc);
                },
                else => {
                    var esc: [4]u8 = undefined;
                    _ = std.fmt.bufPrint(&esc, "\\x{x:0>2}", .{b}) catch unreachable;
                    try out_buf.appendSlice(allocator, &esc);
                },
            }
        }

        const footer_line = try std.fmt.allocPrint(allocator, "\", .mime = \"{s}\" }},\n", .{mime});
        defer allocator.free(footer_line);
        try out_buf.appendSlice(allocator, footer_line);
    }

    try out_buf.appendSlice(allocator, "};\n");

    // Open the output file. The parent dir is created if missing so the
    // step works on a fresh checkout with no `embedded/` dir.
    const out_dir_path = std.fs.path.dirname(out_path) orelse ".";
    const out_basename = std.fs.path.basename(out_path);
    try mkdirsRecursive(out_dir_path);
    const out_fd = try openCreateTrunc(out_dir_path, out_basename);
    defer _ = std.c.close(out_fd);

    // Dump the accumulated buffer with a single raw write(2) syscall.
    var written: usize = 0;
    while (written < out_buf.items.len) {
        const n_rc = std.c.write(out_fd, out_buf.items[written..].ptr, out_buf.items.len - written);
        if (n_rc < 0) return error.WriteFailed;
        const n: usize = @intCast(n_rc);
        if (n == 0) return error.WriteFailed;
        written += n;
    }

    if (dist_exists) {
        std.debug.print("Generated {s} with {d} assets\n", .{ out_path, files.items.len });
    } else {
        std.debug.print("Generated {s} with 0 assets (stub: dist/ was not found; run 'bun run build' to populate)\n", .{out_path});
    }
}

fn lessThan(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, a, b);
}

/// Recursively walk a directory tree and append every regular file's
/// path (relative to `root`) to `out`. Directories are recursed;
/// symlinks are skipped to avoid cycles. Cross-platform: uses
/// POSIX `opendir/readdir/closedir` on Linux + macOS (mirroring the
/// historical POSIX-only implementation), and Win32
/// `FindFirstFileW/FindNextFileW/FindClose` on Windows. (`std.c.readdir`
/// is exposed as `void` on Windows in Zig 0.16 — see the matching
/// `helpers/mod.zig:PosixTimespec` comment for the same pattern.)
fn walkDir(
    allocator: std.mem.Allocator,
    root: []const u8,
    prefix: []const u8,
    out: *std.ArrayList([]const u8),
) !void {
    // `try switch (...) { ... }` propagates the error union
    // returned by both branches. (`switch` is a non-void expression
    // here, so the function body's trailing value needs `try`-ing
    // when the inner returns `!T`.)
    return switch (builtin.os.tag) {
        .windows => walkDirWindows(allocator, root, prefix, out),
        else => walkDirPosix(allocator, root, prefix, out),
    };
}

fn walkDirPosix(
    allocator: std.mem.Allocator,
    root: []const u8,
    prefix: []const u8,
    out: *std.ArrayList([]const u8),
) !void {
    const full_dir = if (prefix.len == 0)
        try allocator.dupe(u8, root)
    else
        try std.fs.path.join(allocator, &.{ root, prefix });
    defer allocator.free(full_dir);

    var open_path_buf: [8192:0]u8 = undefined;
    const open_path = copyToNull(&open_path_buf, full_dir);
    const dir_ptr = std.c.opendir(open_path) orelse return error.OpenDirFailed;
    defer _ = std.c.closedir(dir_ptr);

    while (std.c.readdir(dir_ptr)) |raw_entry| {
        const entry: *std.c.dirent = raw_entry;
        const name = std.mem.sliceTo(&entry.name, 0);

        if (name.len > 0 and !(name.len == 1 and name[0] == '.') and
            !(name.len == 2 and name[0] == '.' and name[1] == '.'))
        {
            const rel = try std.fs.path.join(allocator, &.{ prefix, name });

            if (entry.type == comptime dtValue(.REG)) {
                try out.append(allocator, rel);
            } else if (entry.type == comptime dtValue(.DIR)) {
                try walkDirPosix(allocator, root, rel, out);
            } else {
                allocator.free(rel); // symlinks etc. — skip
            }
        }
    }
}

// Win32 directory walking — uses `FindFirstFileW`/`FindNextFileW`
// from kernel32.dll. These are reachable on Windows only; the
// `extern` decl below is dead-code-eliminated by Zig's
// `builtin.os.tag == .windows` checker at comptime so the symbol
// isn't referenced on Linux/macOS hosts.
extern "kernel32" fn FindFirstFileW(
    lpFileName: [*:0]const u16,
    lpFindFileData: *WIN32_FIND_DATAW,
) callconv(.winapi) ?std.os.windows.HANDLE;
extern "kernel32" fn FindNextFileW(
    hFindFile: std.os.windows.HANDLE,
    lpFindFileData: *WIN32_FIND_DATAW,
) callconv(.winapi) std.os.windows.BOOL;
extern "kernel32" fn FindClose(
    hFindFile: std.os.windows.HANDLE,
) callconv(.winapi) std.os.windows.BOOL;

/// Win32's FIND_DATA structure. The Zig 0.16 stdlib doesn't expose
/// it via `std.os.windows`; we need the raw layout because the
/// `WIN32_FIND_DATAW.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY`
/// bit is the only reliable way to distinguish directories from
/// regular files (the naming convention `name == ".."`-prefix
/// doesn't apply on Windows — directory names are bare).
const WIN32_FIND_DATAW = extern struct {
    dwFileAttributes: u32,
    ftCreationTime: std.os.windows.FILETIME,
    ftLastAccessTime: std.os.windows.FILETIME,
    ftLastWriteTime: std.os.windows.FILETIME,
    nFileSizeHigh: u32,
    nFileSizeLow: u32,
    dwReserved0: u32,
    dwReserved1: u32,
    cFileName: [std.os.windows.MAX_PATH]u16,
    // Trailing `cAlternateFileName` is intentionally omitted — Zig
    // 0.16 doesn't expose it, and we never use it.
};

fn walkDirWindows(
    allocator: std.mem.Allocator,
    root: []const u8,
    prefix: []const u8,
    out: *std.ArrayList([]const u8),
) !void {
    const full_dir = if (prefix.len == 0)
        try allocator.dupe(u8, root)
    else
        try std.fs.path.join(allocator, &.{ root, prefix });
    defer allocator.free(full_dir);

    // Convert the UTF-8 absolute path + an `\*` wildcard (Win32's
    // FindFirstFileW wants the search pattern to include a wildcard
    // to enumerate the directory itself) into a WTF-16 buffer. We
    // size for 2 additional u16 units (`\`, `*`) plus the NUL.
    var full_w: [std.fs.max_path_bytes:0]u16 = undefined;
    // `wtf8ToWtf16Le` returns the count of `u16` units WRITTEN into
    // the destination buffer (`usize`), not a slice. Pre-allocate
    // room for the appended `\*` and trailing NUL.
    const written = std.unicode.wtf8ToWtf16Le(&full_w, full_dir) catch
        return error.OpenDirFailed;
    if (written + 3 > full_w.len) return error.OpenDirFailed; // `\*\0` + 1
    full_w[written] = '\\';
    full_w[written + 1] = '*';
    full_w[written + 2] = 0;

    var find_data: WIN32_FIND_DATAW = undefined;
    const h_opt = FindFirstFileW(@ptrCast(&full_w), &find_data);
    const h = h_opt orelse return error.OpenDirFailed;
    defer _ = FindClose(h);

    while (true) {
        // The file name is `cFileName` — NUL-terminated WTF-16,
        // up to MAX_PATH characters. Slice on first 0.
        const name_w = std.mem.sliceTo(&find_data.cFileName, 0);

        // Skip "." / ".." (FAT filesystem doesn't generate these
        // but a paranoid check costs nothing).
        const is_dot = name_w.len == 1 and name_w[0] == '.';
        const is_dotdot = name_w.len == 2 and
            name_w[0] == '.' and name_w[1] == '.';
        if (!is_dot and !is_dotdot) {
            // Convert WTF-16 back to UTF-8 to use in std.fs.path.join
            // (which is UTF-8 on every host) and to emit the relative
            // path that gets baked into the generated Zig source.
            const name_u8_len = std.unicode.calcWtf8Len(name_w);
            const name_buf = try allocator.alloc(u8, name_u8_len);
            defer allocator.free(name_buf);
            _ = std.unicode.wtf16LeToWtf8(name_buf, name_w);

            const rel = try std.fs.path.join(
                allocator,
                &.{ prefix, name_buf },
            );

            // `dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY` is the
            // MS-DOS-era filesystem directory bit — stable across
            // every Win32-supported filesystem since Windows 95.
            const is_dir = (find_data.dwFileAttributes & 0x10) != 0;
            if (is_dir) {
                try walkDirWindows(allocator, root, rel, out);
            } else {
                try out.append(allocator, rel);
            }
        }

        const more = FindNextFileW(h, &find_data);
        if (more.toBool() == false) break;
    }
}

/// Return the integer `DT_*` value for `kind` (REG | DIR) on the current
/// platform. DT_REG and DT_DIR are values inside `<dirent.h>` and are
/// stable across Linux/macOS (both descend from BSD), so we just match by
/// name. Computed at comptime.
fn dtValue(comptime kind: enum { REG, DIR }) u8 {
    return switch (kind) {
        .REG => 8, // DT_REG
        .DIR => 4, // DT_DIR
    };
}

/// Copy a path into a caller-provided NUL-terminated stack buffer and
/// return a pointer to the start. The caller must keep `buf` alive for
/// the lifetime of the returned pointer (so the buffer must be in the
/// caller's stack frame, not a separate function).
fn copyToNull(buf: *[8192:0]u8, path: []const u8) [*:0]const u8 {
    if (path.len >= buf.len) @panic("path too long for null-terminated buffer");
    @memcpy(buf[0..path.len], path);
    buf[path.len] = 0;
    return buf;
}

/// `mkdir(2)` the given path, creating any missing parents.
fn mkdirsRecursive(path: []const u8) !void {
    if (path.len == 0 or (path.len == 1 and path[0] == '.')) return;

    var path_buf: [8192:0]u8 = undefined;
    const path_z = copyToNull(&path_buf, path);

    // If it already exists, we're done. std.c.access returns 0 on
    // success, -1 on failure (errno set to EEXIST or similar).
    if (std.c.access(path_z, 0) == 0) return;

    // Recurse on the parent first.
    if (std.fs.path.dirname(path)) |parent| {
        if (parent.len < path.len) try mkdirsRecursive(parent);
    }

    // Now mkdir this path. std.c.mkdir returns 0 on success, -1 on
    // failure with errno set. EEXIST is fine (a concurrent creator).
    if (std.c.mkdir(path_z, @as(std.c.mode_t, 0o755)) != 0) {
        const errno_val = std.c.errno(-1);
        if (errno_val != .EXIST) return error.MkdirFailed;
    }
}

/// Open (or create + truncate) a file for writing. Returns the raw fd.
/// Cross-platform: POSIX uses libc `open(2)`; Windows uses Win32
/// `CreateFileW`. Both return the same value (a `std.c.fd_t`) via
/// per-platform extern decl + comptime dispatch.
fn openCreateTrunc(dir_path: []const u8, basename: []const u8) !std.c.fd_t {
    const full = try std.fs.path.join(std.heap.page_allocator, &.{ dir_path, basename });
    defer std.heap.page_allocator.free(full);

    return switch (builtin.os.tag) {
        .windows => openCreateTruncWindows(full),
        else => openCreateTruncPosix(full),
    };
}

fn openCreateTruncPosix(full: []const u8) !std.c.fd_t {
    var buf: [8192:0]u8 = undefined;
    const path_z = copyToNull(&buf, full);
    // Posix `open(path, O_WRONLY|O_CREAT|O_TRUNC, 0o644)`. Flags
    // come straight from `std.c.O` (no Windows type-void issues here
    // — Windows is the comptime-else branch).
    const flags: std.c.O = .{
        .ACCMODE = .WRONLY,
        .CREAT = true,
        .TRUNC = true,
        .CLOEXEC = true,
    };
    const rc = std.c.open(path_z, flags, @as(std.c.mode_t, 0o644));
    if (rc < 0) return error.OpenOutFailed;
    return rc;
}

// Win32 CreateFileW + CloseHandle — declared locally because
// std.os.windows 0.16 doesn't expose `kernel32!CreateFileW` or
// `kernel32!CloseHandle` (the std wraps them per-file under
// different names, e.g. ntdll!ZwCloseHandle for the close path).
// Magic constants from winbase.h:
//
//   GENERIC_WRITE = 0x40000000
//   GENERIC_READ  = 0x80000000
//   FILE_SHARE_READ = 0x1  (allow other readers so dev-server
//                          reloads don't break the build)
//   CREATE_ALWAYS = 2
//   OPEN_EXISTING = 3
//   FILE_ATTRIBUTE_NORMAL = 0x80
extern "kernel32" fn CreateFileW(
    lpFileName: [*:0]const u16,
    dwDesiredAccess: std.os.windows.DWORD,
    dwShareMode: std.os.windows.DWORD,
    lpSecurityAttributes: ?*std.os.windows.SECURITY_ATTRIBUTES,
    dwCreationDisposition: std.os.windows.DWORD,
    dwFlagsAndAttributes: std.os.windows.DWORD,
    hTemplateFile: ?std.os.windows.HANDLE,
) callconv(.winapi) ?std.os.windows.HANDLE;

extern "kernel32" fn CloseHandle(hObject: std.os.windows.HANDLE) callconv(.winapi) std.os.windows.BOOL;

fn closeWindowsHandle(h: std.os.windows.HANDLE) void {
    _ = CloseHandle(h);
}

fn openCreateTruncWindows(full: []const u8) !std.c.fd_t {
    var path_w: [std.fs.max_path_bytes:0]u16 = undefined;
    const written = std.unicode.wtf8ToWtf16Le(&path_w, full) catch
        return error.OpenOutFailed;
    path_w[written] = 0;

    const h_opt = CreateFileW(
        @ptrCast(&path_w),
        0x40000000, // GENERIC_WRITE
        0x1, // FILE_SHARE_READ (so hot-reload windows can read it)
        null,
        2, // CREATE_ALWAYS
        0x80, // FILE_ATTRIBUTE_NORMAL
        null,
    );
    const h = h_opt orelse return error.OpenOutFailed;
    // `std.c.fd_t` is `*anyopaque` on Windows; wrap the HANDLE pointer.
    // lld-link passes the HANDLE through unchanged because both are
    // pointer-sized in x86_64.
    return @ptrFromInt(@intFromPtr(h));
}

/// Read the entire contents of a file into a fresh allocation. Returns
/// the buffer; caller owns it. A safety cap of `max_bytes` is enforced
/// Read the entire contents of a file into a fresh allocation. Returns
/// the buffer; caller owns it. A safety cap of `max_bytes` is enforced
/// to catch runaway inputs. We don't call fstat (Zig 0.16 has no
/// cross-platform fstat — std.c.fstat is `void` on Linux and the stdlib
/// recommends statx instead). Instead, we read incrementally into a
/// growing ArrayList, doubling the read buffer each round and stopping
/// at EOF. Works on every platform the build tool runs on.
fn readFileAll(allocator: std.mem.Allocator, path: []const u8, max_bytes: usize) ![]u8 {
    return switch (builtin.os.tag) {
        .windows => readFileAllWindows(allocator, path, max_bytes),
        else => readFileAllPosix(allocator, path, max_bytes),
    };
}

fn readFileAllPosix(allocator: std.mem.Allocator, path: []const u8, max_bytes: usize) ![]u8 {
    var path_buf: [8192:0]u8 = undefined;
    const path_z = copyToNull(&path_buf, path);

    const flags: std.c.O = .{ .ACCMODE = .RDONLY, .CLOEXEC = true };
    const fd_rc = std.c.open(path_z, flags, @as(std.c.mode_t, 0));
    if (fd_rc < 0) return error.OpenFileFailed;
    const fd: std.c.fd_t = fd_rc;
    defer _ = std.c.close(fd);

    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(allocator);
    try buf.ensureTotalCapacity(allocator, 4 * 1024);
    var total: usize = 0;
    var chunk: [64 * 1024]u8 = undefined;
    while (true) {
        const n_rc = std.c.read(fd, &chunk, chunk.len);
        if (n_rc < 0) return error.ReadFailed;
        const n: usize = @intCast(n_rc);
        if (n == 0) break; // EOF
        if (total + n > max_bytes) return error.FileTooLarge;
        try buf.appendSlice(allocator, chunk[0..n]);
        total += n;
    }
    return buf.toOwnedSlice(allocator);
}

// Windows counterpart — declared locally because std.os.windows 0.16
// doesn't expose `kernel32!ReadFile` or `kernel32!CloseHandle` (the
// std wraps them per-file under different names). Magic constants
// from winbase.h / winnt.h:
//   GENERIC_READ  = 0x80000000
//   FILE_SHARE_READ = 0x1
//   OPEN_EXISTING = 3
//   FILE_ATTRIBUTE_NORMAL = 0x80
extern "kernel32" fn ReadFile(
    hFile: std.os.windows.HANDLE,
    lpBuffer: [*]u8,
    nNumberOfBytesToRead: std.os.windows.DWORD,
    lpNumberOfBytesRead: ?*std.os.windows.DWORD,
    lpOverlapped: ?*std.os.windows.OVERLAPPED,
) callconv(.winapi) std.os.windows.BOOL;

fn readFileAllWindows(allocator: std.mem.Allocator, path: []const u8, max_bytes: usize) ![]u8 {
    var path_w: [std.fs.max_path_bytes:0]u16 = undefined;
    const written = std.unicode.wtf8ToWtf16Le(&path_w, path) catch
        return error.OpenFileFailed;
    path_w[written] = 0;

    const h_opt = CreateFileW(
        @ptrCast(&path_w),
        0x80000000, // GENERIC_READ
        0x1, // FILE_SHARE_READ
        null,
        3, // OPEN_EXISTING
        0x80, // FILE_ATTRIBUTE_NORMAL
        null,
    );
    const h = h_opt orelse return error.OpenFileFailed;
    defer closeWindowsHandle(h);

    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(allocator);
    try buf.ensureTotalCapacity(allocator, 4 * 1024);
    var total: usize = 0;
    var chunk: [64 * 1024]u8 = undefined;
    while (true) {
        var bytes_read: std.os.windows.DWORD = 0;
        const ok = ReadFile(
            h,
            &chunk,
            @intCast(chunk.len),
            &bytes_read,
            null,
        );
        if (ok.toBool() == false) return error.ReadFailed;
        if (bytes_read == 0) break; // EOF
        const n: usize = @intCast(bytes_read);
        if (total + n > max_bytes) return error.FileTooLarge;
        try buf.appendSlice(allocator, chunk[0..n]);
        total += n;
    }
    return buf.toOwnedSlice(allocator);
}

/// MIME type lookup by file extension.
fn inferMime(path: []const u8) []const u8 {
    if (std.mem.endsWith(u8, path, ".html")) return "text/html; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".css")) return "text/css; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".js")) return "application/javascript; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".mjs")) return "application/javascript; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".json")) return "application/json; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".svg")) return "image/svg+xml";
    if (std.mem.endsWith(u8, path, ".png")) return "image/png";
    if (std.mem.endsWith(u8, path, ".jpg") or std.mem.endsWith(u8, path, ".jpeg")) return "image/jpeg";
    if (std.mem.endsWith(u8, path, ".gif")) return "image/gif";
    if (std.mem.endsWith(u8, path, ".webp")) return "image/webp";
    if (std.mem.endsWith(u8, path, ".ico")) return "image/x-icon";
    if (std.mem.endsWith(u8, path, ".woff")) return "font/woff";
    if (std.mem.endsWith(u8, path, ".woff2")) return "font/woff2";
    if (std.mem.endsWith(u8, path, ".ttf")) return "font/ttf";
    if (std.mem.endsWith(u8, path, ".map")) return "application/json; charset=utf-8";
    if (std.mem.endsWith(u8, path, ".txt")) return "text/plain; charset=utf-8";
    return "application/octet-stream";
}
